apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: NodePort
  selector:
    app: nodejs-app
  ports:
    - port: {{ .Values.nodeapp.container.port }}
      targetPort: {{ .Values.nodeapp.container.port }}
      nodePort: {{ .Values.nodeapp.container.nodePort }}
