name: Scan Docker Image with Trivy

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Scan image from registry
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          image-ref: docker.io/evamecobblah/myapp:latest
          format: table
          exit-code: 1
          output: trivy-results.json
          severity: CRITICAL,HIGH

      - name: Upload Trivy results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: trivy-results
          path: trivy-results.json
    

